from Exceptions.ExceptionCustom import ExceptionCustom


class NameGivenException(ExceptionCustom):
    pass
